#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "typer>=0.12",
#   "httpx>=0.27",
#   "pydantic-settings>=2.13",
# ]
# ///
"""Release cut for drape. Generated by project-kit.

Reads .project-kit/cliff.toml, drafts release notes via LiteLLM, tags + pushes,
creates GH release. Owned by this repo — edit freely.
"""

from __future__ import annotations

import json
import re
import shlex
import subprocess
import sys
import tempfile
from collections.abc import Mapping
from pathlib import Path

import httpx
import typer
from pydantic import Field, HttpUrl, SecretStr, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

PROJECT_NAME = "drape"
CLIFF_CONFIG = ".project-kit/cliff.toml"
BRANCH = "main"
LITELLM_MODEL = "deepseek-v4-pro-cloud"
INSTALL_COMMAND = "uv tool install drape=={version}"
# `just version` prod-version resolution (baked from .project-kit answers).
PROD_SOURCE = "none"
PROD_HOMELAB_ENV = ""
BAKED_LITELLM_BASE_URL: HttpUrl | None = None


class Settings(BaseSettings):
    """Validated runtime configuration for release operations."""

    model_config = SettingsConfigDict(
        extra="ignore",
        validate_default=True,
    )

    # Public repos bake no private endpoint, so their default is None and the
    # environment must provide LITELLM_BASE_URL before drafting release notes.
    litellm_base_url: HttpUrl | None = Field(
        default=BAKED_LITELLM_BASE_URL,
        validation_alias="LITELLM_BASE_URL",
    )
    litellm_api_key: SecretStr | None = Field(
        default=None,
        validation_alias="LITELLM_API_KEY",
    )
    openai_api_key: SecretStr | None = Field(
        default=None,
        validation_alias="OPENAI_API_KEY",
    )
    editor: str = Field(default="vim", validation_alias="EDITOR")
    home: Path = Field(default_factory=Path.home, validation_alias="HOME")

    @field_validator("home", mode="before")
    @classmethod
    def _home_must_not_be_empty(cls, value: object) -> object:
        if value == "":
            raise ValueError("HOME must not be empty")
        return value

    @field_validator("litellm_base_url", mode="before")
    @classmethod
    def _empty_url_uses_baked_default(cls, value: object) -> object | None:
        if value == "":
            return BAKED_LITELLM_BASE_URL
        return value

    @field_validator("litellm_api_key", "openai_api_key", mode="before")
    @classmethod
    def _empty_secret_is_unset(cls, value: object) -> object | None:
        return None if value == "" else value

    @field_validator("editor")
    @classmethod
    def _valid_editor(cls, value: str) -> str:
        try:
            argv = shlex.split(value)
        except ValueError as exc:
            raise ValueError("EDITOR must be valid shell-style argv") from exc
        if not argv:
            raise ValueError("EDITOR must contain an executable")
        return value

    @model_validator(mode="after")
    def _legacy_litellm_key(self) -> Settings:
        """Load the legacy key only when neither preferred environment key exists."""
        if self.litellm_api_key or self.openai_api_key:
            return self
        cfg_path = self.home / ".config" / "litellm" / "config.json"
        if not cfg_path.is_file():
            return self
        try:
            decoded = json.loads(cfg_path.read_text())
        except (OSError, json.JSONDecodeError):
            return self
        if not isinstance(decoded, Mapping):
            return self
        value = decoded.get("api_key", "")
        if isinstance(value, str) and value:
            self.litellm_api_key = SecretStr(value)
        return self

    @property
    def llm_api_key(self) -> SecretStr | None:
        return self.litellm_api_key or self.openai_api_key

    @property
    def editor_argv(self) -> list[str]:
        return shlex.split(self.editor)

    def homelab_image_tag(self, relative_env: str) -> tuple[Path, bool, str | None]:
        """Read IMAGE_TAG from the configured HOME-relative homelab env file."""
        env_path = self.home / "Documents" / "Homelab" / relative_env
        if not env_path.is_file():
            return env_path, False, None
        for raw in env_path.read_text().splitlines():
            line = raw.strip()
            if line.startswith("IMAGE_TAG="):
                value = line.split("=", 1)[1].strip().strip('"').strip("'")
                return env_path, True, value
        return env_path, True, None


SETTINGS = Settings()

app = typer.Typer(add_completion=False)


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, check=True, capture_output=True, text=True)


def _current_branch() -> str:
    return _run(["git", "rev-parse", "--abbrev-ref", "HEAD"]).stdout.strip()


def _is_clean() -> bool:
    return _run(["git", "status", "--porcelain"]).stdout.strip() == ""


def _latest_tag() -> str | None:
    try:
        return _run(["git", "describe", "--tags", "--abbrev=0", "--match", "v*"]).stdout.strip()
    except subprocess.CalledProcessError:
        return None


def _next_version(level: str) -> str:
    last = _latest_tag() or "v0.0.0"
    m = re.match(r"v(\d+)\.(\d+)\.(\d+)", last)
    if not m:
        raise typer.Exit(code=1)
    major, minor, patch = map(int, m.groups())
    if level == "major":
        return f"v{major + 1}.0.0"
    if level == "minor":
        return f"v{major}.{minor + 1}.0"
    return f"v{major}.{minor}.{patch + 1}"


def _draft_notes(version: str, prev_tag: str | None) -> str:
    """Draft release notes via the configured LLM endpoint. Empty on failure."""
    base_url = str(SETTINGS.litellm_base_url or "").rstrip("/")
    api_key = SETTINGS.llm_api_key
    try:
        rng = f"{prev_tag}..HEAD" if prev_tag else "HEAD"
        commits = _run(["git", "log", rng, "--pretty=format:- %h %s"]).stdout
        prompt = (
            f"Draft a short, editorial GitHub release narrative for {PROJECT_NAME} {version}.\n"
            f"Commits in this release:\n{commits}\n\n"
            f"{(
                'Install: ' + INSTALL_COMMAND.replace('{version}', version.lstrip('v'))
                if INSTALL_COMMAND else ''
            )}\n"
        )
        r = httpx.post(
            f"{base_url}/chat/completions",
            headers={"Authorization": f"Bearer {api_key.get_secret_value()}"} if api_key else {},
            json={"model": LITELLM_MODEL, "messages": [{"role": "user", "content": prompt}]},
            timeout=30,
        )
        r.raise_for_status()
        return str(r.json()["choices"][0]["message"]["content"])
    except (httpx.HTTPError, KeyError, json.JSONDecodeError) as exc:
        typer.echo(f"[warn] LiteLLM draft failed: {exc}", err=True)
        return ""


def preflight() -> None:
    typer.echo("[1/7] preflight…")
    if not _is_clean():
        typer.echo("error: working tree not clean", err=True)
        raise typer.Exit(code=1)
    branch = _current_branch()
    if branch != BRANCH:
        typer.echo(f"error: on branch {branch}, expected {BRANCH}", err=True)
        raise typer.Exit(code=1)
    if not Path(CLIFF_CONFIG).is_file():
        typer.echo(f"error: {CLIFF_CONFIG} missing", err=True)
        raise typer.Exit(code=1)
    typer.echo("       ok")


@app.command()
def cut(
    level: str = typer.Argument(..., help="patch | minor | major"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    draft: bool = typer.Option(False, "--draft"),
) -> None:
    if level not in ("patch", "minor", "major"):
        typer.echo(f"error: bad level {level}", err=True)
        raise typer.Exit(code=1)
    if not dry_run:
        preflight()
    version = _next_version(level)
    typer.echo(f"[2/7] next version: {version}")
    if dry_run:
        typer.echo(f"[dry-run] would tag {version}, commit changelog, push, gh release create")
        return
    typer.echo("[3/7] regenerating CHANGELOG.md via git-cliff…")
    _run(
        [
            "uvx",
            "git-cliff@latest",
            "--config",
            CLIFF_CONFIG,
            "--output",
            "CHANGELOG.md",
            "--tag",
            version,
        ]
    )
    typer.echo("[4/7] drafting release notes via LiteLLM…")
    notes = _draft_notes(version, _latest_tag())
    typer.echo("[5/7] opening $EDITOR for review…")
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(notes)
        notes_path = f.name
    subprocess.run([*SETTINGS.editor_argv, notes_path], check=False)
    # notes_path is reused below as --notes-file (the editor wrote in place).
    typer.echo("[6/7] commit + tag + push…")
    _run(["git", "add", "CHANGELOG.md"])
    _run(["git", "commit", "-m", f"chore(release): {version}"])
    _run(["git", "tag", "-a", version, "-m", f"release {version}"])
    _run(["git", "push", "origin", BRANCH, "--tags"])
    typer.echo(f"[7/7] gh release create {version}…")
    cmd = ["gh", "release", "create", version, "--notes-file", notes_path]
    if draft:
        cmd.append("--draft")
    _run(cmd)
    typer.echo(f"done. URL: $(gh release view {version} --json url -q .url)")


@app.command()
def version() -> None:
    """Print the local latest tag and the deployed prod version (per prod_source)."""
    typer.echo(f"local:  {_latest_tag() or '(none)'}")
    if PROD_SOURCE == "homelab" and PROD_HOMELAB_ENV:
        env_path, exists, image_tag = SETTINGS.homelab_image_tag(PROD_HOMELAB_ENV)
        label = f"~/Documents/Homelab/{PROD_HOMELAB_ENV} IMAGE_TAG"
        if not exists:
            typer.echo(f"prod:   (file not found: {env_path})   [{label}]")
            return
        if image_tag is None:
            typer.echo(f"prod:   (IMAGE_TAG not set)   [{label}]")
            return
        typer.echo(f"prod:   {image_tag or '(empty)'}   [{label}]")
    elif PROD_SOURCE == "none":
        typer.echo("prod:   (not configured — prod_source = none)")
    else:
        typer.echo(
            f"prod:   (prod_source={PROD_SOURCE!r} " "not supported by this generated release.py)"
        )


@app.command()
def notes(tag: str = typer.Option(..., "--tag")) -> None:
    """Regenerate notes for an existing tag (no commit, no push)."""
    prev = (
        _run(
            ["git", "describe", "--tags", "--abbrev=0", f"{tag}^", "--match", "v*"],
        ).stdout.strip()
        or None
    )
    content = _draft_notes(tag, prev)
    sys.stdout.write(content)


if __name__ == "__main__":
    app()
